name: flutterreddit
description: A flutter reddit app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  draw: ^0.9.1
  mobx: ^1.2.1+1
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.10.0
  flutter_mobx: ^1.1.0+1
  url_launcher: ^5.4.11
  flutter_web_browser: "^0.11.0"
  shared_preferences: ^0.5.10
  cupertino_icons: ^0.1.3
  flutter_webview_plugin: ^0.3.11
  uuid: 2.2.2
  google_fonts: ^1.1.0
  eva_icons_flutter: ^2.0.1
  transparent_image: ^1.0.0
  intl: ^0.15.6
  flutter_markdown: ^0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icon/rettericon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true